config/routes.rb
Bookcuddle::Application.routes.draw do

  root :to => 'users#index'

  resources :discussions, :only => [:create, :destroy, :new, :show, :index]
  resources :users
  resources :sessions, :only => [:create, :destroy]
  resources :books, :only => [:create, :show]

  post 'quotes', to: 'discussions#quote', as: 'quote'
  post 'progress', to: 'discussions#progress', as: 'progress'
  get 'friends', to: 'users#friends', as: 'friends'
  get 'compare/:friend_goodreads_id', to:'users#compare', as:'compare'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'authorized', to: 'sessions#authorized', as: 'authorized'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
end

app/models/user.rb
class User
    include Mongoid::Document
    field :name, type: String
    field :email, type: String
    field :goodreads_id, type: Integer
    field :access_token, type: String
    field :access_token_secret, type: String
    field :friends, type: Array, :default => []

    has_and_belongs_to_many :discussions

    attr_accessible :email, :name, :goodreads_id, :friends

    validates_uniqueness_of :email

    def add_friend(user)
      puts 'add me as a friend!!'
      friend_id = user.id
      if !self.friends.include?(friend_id.to_s)
        self.friends << friend_id.to_s
        self.save
      end
    end

    def self.get_or_create_goodreads_user(goodreads_id, goodreads_name)
      begin
        user = User.find_by(goodreads_id: goodreads_id)
      rescue
        user = User.new(name: goodreads_name, goodreads_id: goodreads_id)
      end
    end
end

app/controllers/users_controller.rb
require 'goodreads_api'

class UsersController < ApplicationController
  include API
  
  before_filter :authorize, :only => [:friends, :compare]
  before_filter :create_connection, :only => [:friends, :compare]
  
  def index
    @users = User.all
  end

  def show
    if request.xhr?
      goodreads_id = params[:id]
      begin
        @user = User.find_by(goodreads_id: goodreads_id.to_i)
        if params[:add_friend] == '1'
          puts 'adding friend!'
          current_user.add_friend(@user)
        end
        @user = {:goodreads_id => goodreads_id}
      rescue
        @user = {:goodreads_id => nil}
      end
    else
      @user = User.find(params[:id])
    end
    respond_to do |format|
      format.html
      format.json {
        render :json => @user.to_json
      }
    end
  end
  
  def new
    if params[:user]
      @user = User.new(:name => params[:user][:goodreads_name], :goodreads_id => params[:user][:goodreads_id])
    else
      @user = User.new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_url
    else
      render "show"
    end
  end
  
  def friends
    @user = current_user
    @friends = @gr_connection.get_user_friends(current_user.goodreads_id.to_s)

    if @friends.empty?  
      flash[:error] = 'Failed to fetch friends'
      puts 'Failed to fetch friends'
      redirect_to signup_path
    end
  end

  def compare
    @user = current_user
    @friend_goodreads_id = params[:friend_goodreads_id]
    @friend = User.find_by(goodreads_id: params[:friend_goodreads_id])
    @comparison = @gr_connection.get_unread_books(params[:friend_goodreads_id])

    #Find books, if not found put books on queue to be created
    @comparison.each do |book|
      Book.find_or_create_by_goodreads(session[:access_token], session[:access_token_secret], book[:id])
    end
  end
  
  private
    def create_connection
      @gr_connection = API::Goodreads.new(session[:access_token], session[:access_token_secret])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.hidden_field :goodreads_id
  .actions
    = f.submit 'Save'

app/views/users/authorized.html.haml
hi!

app/views/users/compare.html.haml
= content_for :head do
  :javascript
    function doAjax() {

      $('tr').each(
        function() {
          var that = $(this);
          var book_id = that.data('book_id');

          // Stripping out the book creation ajax for now
          // var book_url = '/books?id=' + book_id;
          // $.ajax({ url: book_url,
          //          dataType: 'json',
          //          type: 'POST'});

          var friend_id = that.data('friend_id');
          var url = '/discussions/' + book_id + '?friend_id=' + friend_id;
          console.log(url);
          $.ajax({ url: url,
                  type: 'GET',
                  dataType: 'json',
                  cache: false,
                  success: function(data) {
                    // If discussion data is returned
                    if (data['discussion_id'] != null) {
                      // select all the Create Discussions and change to View
                      //get the td
                      var td = that[0];
                      //get the Discussions tr
                      var tr = $(td).find('td[class=discussion]')[0];
                      //change the link
                      var show_link = '/discussions/' + data['discussion_id'];
                      var show_a = $('<a>', {
                        text: 'View',
                        href: show_link,
                        class: 'btn btn-primary'
                      })
                      $(tr).html(show_a);
                    }
                  }
                }
          );
        });
    };

    $(document).ajaxStop($.unblockUI);

    $(document).ready( function() {
      $.blockUI({message: $('#domMessage')});
      doAjax();
    });

%h1
  %i.icon-bookmark{:style => 'padding-top: 15px; padding-right: 15px;'}
  = 'Compare Books with ' + @friend.name

%table.table.table-striped.table-bordered
  %thead
    %tr
      %td
        %b Title
      %td
        %b Your status
      %td
        %b Friend status
      %td
        %b Discussion
  %tbody
  - @comparison.each do |book|
    %tr{:data => {:book_id => book[:id], :friend_id => @friend_goodreads_id } }
      %td
        = link_to book[:title], book[:url]
        %span.small= link_to "(see more)", '#', :class => "see_more", :data => { :book_id => book[:id] }
        .book_info{:style => 'display:none', :data => {:book_id => book[:id] } }
          = "Show me!"
      %td
        = book[:your_review]
      %td
        = book[:their_review]
      %td.discussion
        = link_to "Start", discussions_path({:book_id => book[:id], :book_name => book[:title], :user_2 => @friend_goodreads_id, :user_1 => @current_user.goodreads_id}), :method => :post, :class => 'btn'

%div#domMessage{:style => 'display:none;'}
  %h2 Please wait...

app/views/users/edit.html.haml
%h1
  %i.icon-edit{:style => 'padding-top: 12px; padding-right: 20px;'} 
  Edit Profile

= render 'form'

app/views/users/friends.html.haml
= content_for :head do
  :javascript
    function doAjax() {
      console.log('overrode');

      $('tr').each(
        function() {
          var that = $(this);
          var user_id = that.data('userid');
          var url = '/users/' + user_id + '/?add_friend=1';
          console.log(url);
          $.ajax({ url: url, 
                  type: 'GET',
                  dataType: 'json',
                  cache: false,
                  success: function(data) {
                    // If user data is returned
                    if (data['goodreads_id'] != null) {
                      // select all the Invites and change to Compare

                      //get the td
                      var td = that[0];
                      //get the Invite tr
                      var tr = $(td).find('td[class=compare]')[0];
                      //get the Invite a
                      var tr_a = $(tr).find('a');
                      //change the link HTML to 'Compare', change styling
                      tr_a.html('Compare');
                      tr_a.attr('class', 'btn btn-primary');
                      tr_a.css('color', 'white');
                      //change the link
                      var compare_link = '/compare/' + data['goodreads_id'];
                      tr_a.attr('href', compare_link);
                    }
                  }
                }
          );
        });
    };

    $(document).ajaxStop($.unblockUI);

    $(document).ready( function() {
      $.blockUI({message: $('#domMessage')});
      doAjax();
    });

%h1
  %i.icon-group{:style => 'padding-top: 15px; padding-right: 20px;'}
  My Friends

%table.table.table-striped.table-bordered
  - @friends.each do |friend|
    %tr{:data => {:userid => friend[:goodreads_id]}}
      %td
        = image_tag(friend[:photo_url])
      %td
        = link_to friend[:name], "#"
      %td
        = link_to "Goodreads Profile", "http://goodreads.com/user/show/#{ friend[:goodreads_id] }"
      %td.compare
        %a.btn Invite

%div#domMessage{:style => 'display:none;'}
  %h2 Please wait...

app/views/users/index.html.haml
%div.hero-unit
  %h1 
    %i.icon-book{:style => 'padding-top: 28px; padding-right: 28px;'}
    Bookcuddle
    %small Read books together :)

app/views/users/new.html.haml
%h1 New user
= render 'form'
%br
= link_to image_tag('goodreads-login-button.png'), sessions_path, :method => :post
%br
= link_to 'Back', users_path

app/views/users/show.html.haml
%h1
  %i.icon-user{:style => 'padding-top: 12px; padding-right: 20px;'}
  My Profile

%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email