config/routes.rb
Bookcuddle::Application.routes.draw do

  root :to => 'users#index'

  resources :discussions, :only => [:create, :destroy, :new, :show, :index]
  resources :users
  resources :sessions, :only => [:create, :destroy]
  resources :books, :only => [:create, :show]

  post 'quotes', to: 'discussions#quote', as: 'quote'
  post 'progress', to: 'discussions#progress', as: 'progress'
  get 'friends', to: 'users#friends', as: 'friends'
  get 'compare/:friend_goodreads_id', to:'users#compare', as:'compare'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'authorized', to: 'sessions#authorized', as: 'authorized'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    © 2012 Rab and Dag
  %nav
    %ul
      %li
        = link_to "About", about_path
      %li
        = link_to "Contact", contact_path
      %li
        = link_to "Help", "#"

app/views/layouts/_top_nav.html.haml
%div.navbar
  %div.navbar-inner
    %a.brand{:href => "/"} Bookcuddle
    %div.nav-collapse
      %ul.nav
        -if current_user
          %li
            = link_to 'Books', '#'
          %li
            = link_to 'Friends', friends_path
          %li
            = link_to 'Discussions', discussions_path

    %div.pull-right
      %ul.nav
        - if current_user
          %li.dropdown
            %a{:href => '#', :class => 'dropdown-toggle', :data => {:toggle => 'dropdown', :target => '#'}}
              Profile
              %b.caret
            %ul.dropdown-menu.pull-right
              %li
                = link_to 'Edit Profile', edit_user_path(current_user)
                = link_to "Goodreads Profile", "http://goodreads.com/user/show/#{ current_user.goodreads_id }", :target => "_blank"
                = link_to raw('Log out <i class="icon-off" style="padding-top:2px;"></i>'), logout_path
        - else
          #loginButton= link_to image_tag('goodreads-login-button.png'), sessions_path, :method => :post

app/views/layouts/application.html.haml
<!DOCTYPE html>

%html
  %head
    %title Bookcuddle

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    :javascript
      $(document).ready( function() {
        $('.dropdown-toggle').dropdown();
      });

    = yield :head



  %body
    = render :partial => 'layouts/top_nav'


    %div.container
      = yield
      = render :partial => 'layouts/footer'


    %div#domMessage{:style => 'display:none;'}
      %h1 We are default!